### ISSUE TITLE
登陆页面css冲突

### ISSUE THREAD

**Issue by Wine-in-June** [ant-design-blazor/ant-design-pro-blazor#102]
为什么我用模板创建的项目有css冲突，登陆页面无法应用样式啊？改razor页面的内容，浏览器还无法相应更改，必须重启项目才生效？

**Comment by ElderJames** [comment]
你好，你用什么选项创建项目？使用vs2022和.net6就可以热重载。

**Comment by Wine-in-June** [comment]
我用的vs2022,.net5不行，还有userlayout.razo里的css样式都不起作用

**Comment by ElderJames** [comment]
我有空会看看的。你可以先下载源码下来使用。
或者您如果有兴趣，欢迎帮忙调试一下。

**Comment by Wine-in-June** [comment]
好的

**Comment by Wine-in-June** [comment]
antdesign.proLayout(0.1.8)里的antdesign.dll里的Placement.Top;有点问题引起报错，以前的版本是PlacementType.Top;
	public Tooltip()
	{
		//IL_0006: Unknown result type (might be due to invalid IL or missing references)
		//IL_000b: Unknown result type (might be due to invalid IL or missing references)
		base.PrefixCls = "ant-tooltip";
		base.Placement = Placement.Top;
	}

**Comment by ElderJames** [comment]
欢迎提交一个PR .😊

**Comment by ElderJames** [comment]
fixed in #111
