### ISSUE TITLE
Setting panel shows in release

### ISSUE THREAD

**Issue by petrv7** [ant-design-blazor/ant-design-pro-blazor#104]
When you open the settings panel, it says "Setting panel shows in development environment only, please manually modify", but when I switch to release, the settings panel is still there. Is there any way to disable it?

**Comment by anddrzejb** [comment]
I don't really know what was the original intention here, but you are right, it does show. It is added in `BasicLayout.razor` file (component `SettingDrawer`). You can either try to remove it from there or possibly wrapping it in compiler pre-processor directive might work? Another way is to inject `IHostEnvironment` and condition rendering on `IsDevelopment()` method.

**Comment by petrv7** [comment]
> I don't really know what was the original intention here, but you are right, it does show. It is added in `BasicLayout.razor` file (component `SettingDrawer`). You can either try to remove it from there or possibly wrapping it in compiler pre-processor directive might work? Another way is to inject `IHostEnvironment` and condition rendering on `IsDevelopment()` method.

I missed it in the `BasicLayout.razor` file, thanks for pointing that out. It can be easily removed from there. The issue still stands though, the panel should be disabled in production environment.

**Comment by anddrzejb** [comment]
I think the panel should be disabled based on a setting. I can imagine some developers to keep panel available to the users.
