### ISSUE TITLE
无法从“AntDesign.PlacementType”转换为“AntDesign.Placement”

### ISSUE THREAD

**Issue by shuangbaojun** [ant-design-blazor/ant-design-pro-blazor#105]
升级最新版本（0.1.9）报错，如下图所示：
![image](https://user-images.githubusercontent.com/64063254/140697931-744a5397-6ff4-4a29-b8cd-99c0359a2be4.png)

**Comment by ElderJames** [comment]
你好，把 `PlacementType` 改为 `Placement` 即可。
