### ISSUE TITLE
国际化功能未生效

### ISSUE THREAD

**Issue by shuangbaojun** [ant-design-blazor/ant-design-pro-blazor#107]
截图如下：
![image](https://user-images.githubusercontent.com/64063254/140711832-2f950c46-7e41-430c-bc25-25b345275107.png)
另外：
能否在samples里增加国家化示例呢？

**Comment by lifeng2400** [comment]
我也发现这个问题 无法切换语言

**Comment by ElderJames** [comment]
Hi @shuangbaojun , @lifeng2400 . You now need to get i18n functionality from documented source code.
https://github.com/ant-design-blazor/ant-design-blazor/tree/master/site/AntDesign.Docs/Localization
