### ISSUE TITLE
版本升级最新报错-AntDesign.ProLayout。BasicLayout'没有与Body名称匹配的属性。

### ISSUE THREAD

**Issue by shuangbaojun** [ant-design-blazor/ant-design-pro-blazor#108]
开发环境：vs2022+.net5

报错截图如下：
![image](https://user-images.githubusercontent.com/64063254/140881864-074d0d1c-cf22-4158-b4b1-d711d46ef5c8.png)

**Comment by niunan** [comment]
请教最后是怎么解决的呀。
