### ISSUE TITLE
install command-line error

### ISSUE THREAD

**Issue by HUGHNew** [ant-design-blazor/ant-design-pro-blazor#109]
Following the doc to install template, a error that "no matchs found" occured.

doc location:
[en-US](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/docs/introduce.en-US.md#-installation-guide)
[zh-CN](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/docs/introduce.zh-CN.md#%E4%BB%8E%E6%A8%A1%E6%9D%BF%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E6%96%B0%E9%A1%B9%E7%9B%AE)

It seems it works without the suffix **"-\*"**

environment:
Ubuntu 20.04LTS
shell : zsh
dotnet version 6.0.100

```bash
 λ >  dotnet new --install AntDesign.Templates::0.1.0-* 
zsh: no matches found: AntDesign.Templates::0.1.0-*
```

```bash
 λ >  dotnet new --install AntDesign.Templates::0.1.0
The following template packages will be installed:
   AntDesign.Templates::0.1.0

Success: AntDesign.Templates::0.1.0 installed the following templates:
Template Name          Short Name  Language  Tags          
---------------------  ----------  --------  --------------
Ant Design Pro Bla...  antdesign   [C#]      Ant Design Pro
```

So, what cause this error and if there's any diff between "AntDesign.Templates::0.1.0-*" and "AntDesign.Templates::0.1.0" ?

**Comment by ElderJames** [comment]
Thanks for contacting us @HUGHNew 
You can install the latest version now and no need to specific the preview version.

`dotnet new -i AntDesign.Templates`

**Comment by HUGHNew** [comment]
Got, thx
