### ISSUE TITLE
Missing prolayout.css file

### ISSUE THREAD

**Issue by ronikurnia1** [ant-design-blazor/ant-design-pro-blazor#11]
GET https://localhost:5001/_content/AntDesign.Pro.Layout/css/prolayout.css net::ERR_ABORTED 404

**Comment by ronikurnia1** [comment]
It should be **ant-design-pro-layout-blazor.css** instead of prolayout.css

**Comment by ElderJames** [comment]
Thank you @ronikurnia1 !
You just feel free to create a PR.

**Comment by ronikurnia1** [comment]
Hi @ElderJames, done!
See if it as supposed to be
