### ISSUE TITLE
Check box dynamic binding makes it impossible to select

### ISSUE THREAD

**Issue by shuangbaojun** [ant-design-blazor/ant-design-pro-blazor#110]
Background:
Check box dynamic binding makes it impossible to select

Description of the problem:
It is possible to request a variable binding in the background, but if you dynamically bind through a data source on the rasor page, the check box cannot be selected, as shown in the following image:

![image](https://user-images.githubusercontent.com/64063254/144585508-ce2e8ed9-bf9c-47eb-abf3-d54f36857c8e.png)

**Comment by ElderJames** [comment]
This is blazor limitation.
