### ISSUE TITLE
Demo运行异常

### ISSUE THREAD

**Issue by SniperChan** [ant-design-blazor/ant-design-pro-blazor#113]
在通过模板，创建了一个Server程序，选择了full page，一运行程序就报错，如下：

SalesCard.razor.cs

        private async Task OnTabChanged(string activeKey)
        {
            var data = await ChartService.GetSalesDataAsync();
            if (activeKey == "1")
                _**await _saleChart.ChangeData(data);**_
            else
                await _visitChart.ChangeData(data);
        }

await _saleChart.ChangeData(data); 处报错：
System.NullReferenceException:“Object reference not set to an instance of an object.”

开发环境：
Microsoft Visual Studio Enterprise 2022 (64 位) 
版本 17.0.5

**Comment by johnayling** [comment]
**Steps to reproduce**
dotnet new antdesign -o MyAntDesignApp --host server --full
The template "Ant Design Pro Blazor App" was created successfully.

Open .csproj with VS2022 (17.0.5).
Run/debug with IIS Express.

Same issue as @SniperChan.

**Comment by bshhr** [comment]
```
protected override async Task OnInitializedAsync()
{
    await base.OnInitializedAsync();
    //await OnTabChanged("1");
}
```
将`await OnTabChanged("1");`注销了就好了。

**Comment by Refactoring** [comment]
问题还存在： 注释后，可以进入首页，点击任意菜单，进入else逻辑,  这时候_visitChart又是null。
