### ISSUE TITLE
Update newest Antdesign for Antdesign Pro

### ISSUE THREAD

**Issue by hohoan** [ant-design-blazor/ant-design-pro-blazor#123]
Please update newest Antdesign for Antdesign pro and update to nuget.
Thanks team.

**Comment by ElderJames** [comment]
Ok, we will release a new version and update the Pro Template later.

**Comment by ElderJames** [comment]
Hi @hohoan ,we have been update the pro template, please see https://github.com/ant-design-blazor/ant-design-pro-blazor/releases/tag/0.10.6
