### ISSUE TITLE
Some broken CSS after clean installation from the template

### ISSUE THREAD

**Issue by arsinclair** [ant-design-blazor/ant-design-pro-blazor#125]
When installing from this template `dotnet new antdesign -f -o projectname`, somehow the site looks a bit broken. It looks like some css may be missing.

![Peek 2022-05-18 05-02](https://user-images.githubusercontent.com/2878904/168948521-fdc539fc-90c6-431d-9980-509a3ab39a0c.gif)

The same components on https://pro.antblazor.com look absolutely fine.

What could be the issue?

**Comment by arsinclair** [comment]
I noticed that the very last import in the `<head>` of my index.html is `<link href="projectname.styles.css" rel="stylesheet" />` however there's no physical file like this. Is there something that should generate it?

**Comment by ElderJames** [comment]
Hi @arsinclair , yes, our tempalte is default to use CSS , and our online site is use Less, So it's possible that some CSS is broken.

Would you like to take a look for us, please?

**Comment by ElderJames** [comment]
I think CSS isolation is a problem , they change children components in *.razor. CSS require ::deep, so CSS issues are a bit trickier when it comes to changing children component styles. However, the CSS generated by less files is global,so it's fine.

**Comment by arsinclair** [comment]
Okay, so this is a bug in this repo, technically.

Do you have any ideas why the login pages looks funny?

**Comment by arsinclair** [comment]
Yikes! I went down the rabbit hole of digging what could be the issue. There's no problem with the template, but there's with the dotnet. According to https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0#css-isolation-bundling:

> At build time, a project bundle is created with the convention `obj/{CONFIGURATION}/{TARGET FRAMEWORK}/scopedcss/projectbundle/{ASSEMBLY NAME}.bundle.scp.css`
> 
> `{CONFIGURATION}`: The app's build configuration (for example, Debug, Release).
> `{TARGET FRAMEWORK}`: The target framework (for example, net6.0).
> `{ASSEMBLY NAME}`: The app's assembly name (for example, BlazorSample).

I checked if I have this file, and `new-project.styles.css` is there indeed. Then I went to the index.html and checked if the file is imported. Here's what I see: `<link href="new_project.styles.css" rel="stylesheet" />`. As you see, _dotnet_ replaced the dash with an underscore. That's why the file wasn't found in my second comment.

It is probably related to https://github.com/dotnet/templating/issues/1168 and looks like the bug is still there, at least for some files like this, but I'm too tired to report it to Microsoft and carry the ticket through. If anyone wants to do it - the liberty is yours.

With that being that, this is not a problem with this template, and for me personally the solution is to just rename the import to `<link href="new-project.styles.css" rel="stylesheet" />` (replace the underscore with the dash).

Thanks for your attention!

**Comment by ElderJames** [comment]
But we still need to fix the styles so that the templates work out of the box.

**Comment by arsinclair** [comment]
> But we still need to fix the styles so that the templates work out of the box.

Yes, but it is not in our hands. The issue I'm experiencing is for two reasons:

- because my project has a dash in its name
- because there's a bug somewhere in _dotnet_ that creates an incorrect linking between the produced _.css_ file and an _index.html_ file

The best we can do on our side is to document this case and tell the users that a linking needs to be corrected manually.

**Comment by arsinclair** [comment]
If there's another _.css_ issue that I'm not aware of, maybe a separate issue should be created. When I fixed the linking between the _.css_ and _.html_ file in my project, I am not experiencing any other issues, neither with _less_, nor with default _css_-based projects.

**Comment by ElderJames** [comment]
Ok, it's fine. 😀
