### ISSUE TITLE
package.json is copied to the output directory

### ISSUE THREAD

**Issue by arsinclair** [ant-design-blazor/ant-design-pro-blazor#127]
_package.json_ and _package-lock.json_ files are copied to the output (`bin/Debug/net6/`) directory when `npm run start` is executed. They are also copied to the `dist/` directory when `npm run build` is executed.

This produces an unnecessary clutter in the VSCode _NPM Scripts_ section:

![image](https://user-images.githubusercontent.com/2878904/169191724-ead5c2f7-0dba-43e8-a244-8f3855a205b7.png)

Is there any need for these files to be in the output folder? Can they be excluded from the build?

**Comment by ElderJames** [comment]
Yes, if user choose to use css, they won't need the package.json, but if they choose less, they need it.

**Comment by ElderJames** [comment]
Oh, we no nedd the package.json in the output directory

**Comment by arsinclair** [comment]
> Oh, we no nedd the package.json in the output directory

Good to know, I will take a look how it can be excluded from the build, then.
