### ISSUE TITLE
GET https://localhost:5001/css/site.css net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by xuanhe168** [ant-design-blazor/ant-design-pro-blazor#129]
GET https://localhost:5001/css/site.css net::ERR_ABORTED 404
GET https://localhost:5001/AntDesign.Pro.Template.styles.css net::ERR_ABORTED 404

![image](https://user-images.githubusercontent.com/37821420/170666907-c9b47255-5fd8-4f64-8fce-849b288bbb1b.png)

**Comment by ElderJames** [comment]
Hi @mingyouzhu , how can I reproduce this issue?

**Comment by mingyouzhu** [comment]
> Hi @mingyouzhu , how can I reproduce this issue?

Solved because I tampered with the framework code and now I forgot what I changed haha
