### ISSUE TITLE
左侧菜单如何自动折叠?

### ISSUE THREAD

**Issue by mingyouzhu** [ant-design-blazor/ant-design-pro-blazor#136]
AntDesign.ProLayout.BasicLayout  左侧菜单如何自动折叠?
目前demo点击多个菜单后全部展开了 不会自动折叠

**Comment by ElderJames** [comment]
Please see https://antblazor.com/components/menu#components-menu-demo-sider-current2

**Comment by onsuper** [comment]
see https://antblazor.com/components/menu#components-menu-demo-sider-current2

使用链接中相同代码, Blazor使用无效

**Comment by onsuper** [comment]
&nbsp;感谢你的答疑, Nuget 目前没有这个0.15.0版本







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design-blazor/ant-design-pro-blazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月23日(星期二) 晚上11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design-blazor/ant-design-pro-blazor] 左侧菜单如何自动折叠? (Issue #136)





 
Please update to 0.15.0
