### ISSUE TITLE
关闭主题设置之后错位

### ISSUE THREAD

**Issue by shuaqq2004** [ant-design-blazor/ant-design-pro-blazor#140]
https://pro.antblazor.com/
官方演示demo，
在修改了颜色，触发加载新主题之后， 关闭设置drawer。 就出现如下图。

![image](https://user-images.githubusercontent.com/3870105/191640997-3ffdc959-d7ec-48b3-8138-78cab50bda94.png)

**Comment by SimonGuo1122** [comment]
+1
When change to realdark mode, error occurs as above picture.
And theme page cannot close by close button at top left  position.
切换到暗黑主题会出现上面截图的错误，官网会出现同样的错误。https://pro.antblazor.com/
主题设置页的关闭按钮不好用。

**Comment by scx1125** [comment]
如果用最新版本的ant design 14.0开始，只要引用SettingDrawer就会出BUG，一整个遮罩覆盖网页，啥都点不了

**Comment by ElderJames** [comment]
没问题了
