### ISSUE TITLE
能否在demo中添加国际化功能的使用案例？ 现在切换语言无效。

### ISSUE THREAD

**Issue by lsx1994** [ant-design-blazor/ant-design-pro-blazor#149]

**Comment by dongyanming** [comment]
啥时候你能给个简单的Demo也可以啊，谢谢

**Comment by lsx1994** [comment]
> 啥时候你能给个简单的Demo也可以啊，谢谢
自己添加一个select吧... 使用LocaleProvider.SetLocale切换内置文本的语言，自己的文本我直接用全局的Dictionary去访问了。。
