### ISSUE TITLE
菜单的icon不显示

### ISSUE THREAD

**Issue by fuchengzhou** [ant-design-blazor/ant-design-pro-blazor#151]
我使用了 iconfont的icon，在page页是显示的，传入菜单的ICON不显示 ，感觉是没找到SVG 会是哪里的问题

**Comment by 22140505** [comment]
原因应该是：
https://github.com/ant-design-blazor/blazor-pro-components/blob/master/src/layout/src/SiderMenu/BaseMenu.razor 53行
