### ISSUE TITLE
[new] Ant Design Blazor 中的 ReuseTabs 组件

### ISSUE THREAD

**Issue by onsuper** [ant-design-blazor/ant-design-pro-blazor#154]
see https://mp.weixin.qq.com/s/J1vQv_YHUDx6ignlvVVDXA
标签功能能否接入

**Comment by littlelioncjt** [comment]
这功能挺重要的，缺了用户操作都不习惯了，希望能集成进来

**Comment by ElderJames** [comment]
Hello @onsuper @littlelioncjt , we have add the ReuseTabs to the template.
