### ISSUE TITLE
not compatible with .NET 8 (Auto Server and WebAssembly)

### ISSUE THREAD

**Issue by Zero-Xiong** [ant-design-blazor/ant-design-pro-blazor#164]
The step:
1) create new solution, select the default Blazor Web App
2) select .NET 8,  Interactive render mode (Auto Server and WebAssembly)
3) modify the default MainLayout
4) debug, you will see the sider collapsible is not working.

attached is the cods.

[Cashbook.zip](https://github.com/ant-design-blazor/ant-design-pro-blazor/files/13433038/Cashbook.zip)

**Comment by ElderJames** [comment]
Thanks for contacting us @Zero-Xiong , you need to setup the global interactive for `Routes` component.

```
   <Routes  @rendermode="RenderMode.InteractiveAuto" />
```

**Comment by Zero-Xiong** [comment]
> Thanks for contacting us @Zero-Xiong , you need to setup the global interactive for `Routes` component.
> 
> ```
>    <Routes  @rendermode="RenderMode.InteractiveAuto" />
> ```

It works if set rendermode in Routes.

But if use ReuseTabs, the first loading wont show anything

**Comment by ElderJames** [comment]
Yes, this is because the cascadeing route data can't be transfer to the client side. We will achieve this in a later update.

**Comment by ElderJames** [comment]
You can also set rendermode for root component
```
   <Routes  @rendermode="RenderMode.InteractiveAuto" />
```
