### ISSUE TITLE
Error CS0115

### ISSUE THREAD

**Issue by FreddyFox1** [ant-design-blazor/ant-design-pro-blazor#165]
After try scaffold Identity pages, i got error.

![image](https://github.com/ant-design-blazor/ant-design-pro-blazor/assets/35505083/c3dac9b8-fe90-4e78-a388-76bc2b9108e4)

Some erros i got if i try build project in Visual Studio  2022. 
JetBrains Rider building good

**Comment by FreddyFox1** [comment]
Yes, it is first what i do :) 
But nothing.
All updates are installed.

![image](https://github.com/ant-design-blazor/ant-design-pro-blazor/assets/35505083/e95f12aa-236d-4960-b28a-55d82a75b53e)

**Comment by ElderJames** [comment]
How about using the CLI to build the project?

**Comment by FreddyFox1** [comment]
I think i found reason.
This part 
![image](https://github.com/ant-design-blazor/ant-design-pro-blazor/assets/35505083/c93ac1c1-f34d-4cca-9bc5-82674419a1f1)

After delete this 

![image](https://github.com/ant-design-blazor/ant-design-pro-blazor/assets/35505083/8a429469-4994-43d6-bd56-409a2bf01a55)

Now its building.

**Comment by FreddyFox1** [comment]
The solution I found involves exclude pages folder from project and add scaffolded identity items.

**Comment by ElderJames** [comment]
Thanks @FreddyFox1!, could you please help us fix this?

**Comment by FreddyFox1** [comment]
Simple guide to fix it.

1. Update SDK
2. Update VS 2022
3. Try
4. If not success, try to exclude pages and add scaffolded items
