### ISSUE TITLE
菜单栏折叠按钮不起作用

### ISSUE THREAD

**Issue by ghost** [ant-design-blazor/ant-design-pro-blazor#168]
我按照示例做了个demo，但我发现点击折叠菜单的按钮不起作用。basic layout如下
![image](https://github.com/ant-design-blazor/ant-design-pro-blazor/assets/19233629/eb66483c-0e06-439c-8dd6-bc91983fafd4)
运行后，点击按钮没有反应
![image](https://github.com/ant-design-blazor/ant-design-pro-blazor/assets/19233629/a3580f96-d077-4e17-9915-ef830644079a)
不知道是否遗漏了什么，谢谢。
附上源码，谢谢
[HappyIncentive.Web.zip](https://github.com/ant-design-blazor/ant-design-pro-blazor/files/13670913/HappyIncentive.Web.zip)

**Comment by ElderJames** [comment]
模板没问题
