### ISSUE TITLE
Bug when using CheckboxGroup in Form

### ISSUE THREAD

**Issue by Forfires** [ant-design-blazor/ant-design-pro-blazor#175]
I'm trying 0.18.0, I'm using CheckboxGroup in FormItem, and I'm getting the following error, the same code, if using 0.17.4, works fine。
```
 <Form Model="@model"
       LabelColSpan="6"
       WrapperColSpan="12"
       ValidateMode="@FormValidateMode.Rules" 
       ValidateOnChange> 
  <FormItem Label="测试" Required Rules="@(new FormValidationRule[]{ new FormValidationRule {  Required = true, Type= FormFieldType.Array, Message = "故障点不可为空" }})">
         <CheckboxGroup @bind-Value="@context.Detail" >
          <Checkbox Label="Apple" />
          <Checkbox Label="Peer" /> 
      </CheckboxGroup>
  </FormItem>
  </Form>
```

**Comment by ElderJames** [comment]
Thanks for contacting us @Forfires , what error did you met?

**Comment by Forfires** [comment]
Sorry, forgot to paste my error message

> at System.OrdinalCaseSensitiveComparer.GetHashCode(String obj) at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.GetHashCode() at System.Collections.Generic.Dictionary`2.FindValue(TKey key) at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value) at Microsoft.AspNetCore.Components.Forms.EditContext.GetOrAddFieldState(FieldIdentifier& fieldIdentifier) at Microsoft.AspNetCore.Components.Forms.EditContext.NotifyFieldChanged(FieldIdentifier& fieldIdentifier) at AntDesign.AntInputComponentBase`1.set_CurrentValue(TValue value) at AntDesign.AntInputBoolComponentBase.ChangeValue(Boolean value) at AntDesign.Checkbox.InputCheckedChange(ChangeEventArgs args) at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task) at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
