### ISSUE TITLE
--host 不受支持。 无法安装 server，该包不存在。

### ISSUE THREAD

**Issue by shushu789** [ant-design-blazor/ant-design-pro-blazor#177]
PS E:\Working\VScode\blazordemo> dotnet new -i AntDesign.Templates --host server
警告: 已弃用“dotnet new --install”。请改用“dotnet new install”。
有关详细信息，请运行:   
   dotnet new install -h

将安装以下模板包:     
   AntDesign.Templates
   --host
   server

成功: AntDesign.Templates::0.17.3 已安装以下模板:
模板名                     短名称     语言  标记
-------------------------  ---------  ----  --------------
Ant Design Pro Blazor App  antdesign  [C#]  Ant Design Pro

--host 不受支持。
无法安装 server，该包不存在。

请问这个模板不支持blazor server吗？

**Comment by ElderJames** [comment]
支持的，请使用命令

```
 dotnet new antdesign -o MyAntDesignBlazor --host server
```

**Comment by shushu789** [comment]
谢谢你，这很有帮助！
