### ISSUE TITLE
ModalService调用ModalService.CreateModal, ModalService.Error 等均无法显示出来弹框

### ISSUE THREAD

**Issue by scugzbc** [ant-design-blazor/ant-design-pro-blazor#185]
弹窗不能显示出来，详见附件，使用的是官方截止2.24-7-23最新的Tempalte创建的，而且使用了文档里的案例。
弹不出来。
[testapp.zip](https://github.com/user-attachments/files/16339552/testapp.zip)
以前的老版本是可以弹出来的。
![52c184a6f0813560137bddb7d1ff4a64](https://github.com/user-attachments/assets/a187ca06-4dfa-4834-a363-9e987a2fba81)
![QQ_1721707602664](https://github.com/user-attachments/assets/2bb176cd-ec4f-44dd-bfcf-0330083e5087)
以为是要在布局页面里添加一个标签，看文档里没这个说明，在pro项目里也没有自带。
查看所有的js,css都能正常下载。
能想到的原因，就只有这个ModalService实现有bug来解释了。

**Comment by scugzbc** [comment]
下载了Ant.Design项目的源码后，找到了这个，解决了问题。
![QQ_1721726820564](https://github.com/user-attachments/assets/973e2cda-4b21-471e-926e-529603fe5bcb)
要在Routers.razor里添加一个<AntCotainer/>，问题得到解决。

**Comment by ElderJames** [comment]
@scugzbc 请问创建时用了什么参数？

**Comment by ElderJames** [comment]
已经加上了，谢谢！
