### ISSUE TITLE
页面大小变化后左侧选中菜单栏选中状态会丢失（版本>=0.18.2）

### ISSUE THREAD

**Issue by xiaohuu** [ant-design-blazor/ant-design-pro-blazor#197]
AntDesign.ProLayout版本0.18.2-0.20.3存在bug：页面大小变化后左侧选中菜单栏选中状态会丢失。

1. 正常状态：
![正常](https://github.com/user-attachments/assets/b26665ba-518c-457d-bed0-e99ce6aff035)

2. 拖动窗口导致窗口大小变化后，左侧选中菜单栏选中状态丢失状态：
![状态丢失](https://github.com/user-attachments/assets/e3463794-c3ff-4436-8e3c-89d4f5500e67)

打开任意一个页面，调整窗口大小后，左侧选中的菜单栏“选中”状态都会丢失，F5刷新页面后，丢失的选中状态又会恢复正常，0.18.1版本是正常的。

**Comment by ElderJames** [comment]
duplicated with https://github.com/ant-design-blazor/ant-design-blazor/issues/4190.
