### ISSUE TITLE
[BUG] Install Template Failed when ProjectName not equal "AntDesign.Pro"

### ISSUE THREAD

**Issue by gmij** [ant-design-blazor/ant-design-pro-blazor#21]
`
dotnet new antdesign --host=wasm --full
The template "Ant Design Pro Blazor App" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on R:\t1\AntDesign.Pro.csproj...
MSBUILD : error MSB1009: 项目文件不存在。
开关:R:\t1\AntDesign.Pro.csproj

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
`

**Comment by gmij** [comment]
when projectName or folderName is AntDesign.Pro,  No Problem.

when projectName or folderName not equal AntDesign.Pro, template has create project file, but has one error, not restore project.

**Comment by ElderJames** [comment]
Thanks for contacting us @gmij , we have fixed this in PR #22 .
