### ISSUE TITLE
我应当如何做，能实现原版PRO的响应式菜单。

### ISSUE THREAD

**Issue by chinasqzl** [ant-design-blazor/ant-design-pro-blazor#25]
小白请教：
![image](https://user-images.githubusercontent.com/16968103/97273499-6bdc4900-186e-11eb-9616-232738ebe9d5.png)
![image](https://user-images.githubusercontent.com/16968103/97273537-7ac2fb80-186e-11eb-8427-22656f46ac75.png)

主要手机的时候：
![image](https://user-images.githubusercontent.com/16968103/97273587-8adadb00-186e-11eb-9a9a-948854e97f01.png)

**Comment by yoli799480165** [comment]
We will support responsive layouts in the near version, which are not supported yet.

**Comment by chinasqzl** [comment]
谢谢
