### ISSUE TITLE
Getting rid of package.json

### ISSUE THREAD

**Issue by happy1836** [ant-design-blazor/ant-design-pro-blazor#28]
系统能去掉package.json，谢谢

**Comment by ElderJames** [comment]
您好 @happy1836 ,感谢关注！

目前还需要使用 npm 构建的原因主要是编译less文件。如果您不需要覆盖原来less文件中的变量，是可以直接写css的。
我们也一直在探讨不依赖node 的开发流程。

如果有更好的方法，欢迎提交PR。
