### ISSUE TITLE
Unable to modify the target framework to .Net 5.0

### ISSUE THREAD

**Issue by fan0217** [ant-design-blazor/ant-design-pro-blazor#30]
无法修改目标框架至.net5.0

**Comment by yoli799480165** [comment]
我们将在下个版本把pro全部升级到.NET5。

**Comment by ElderJames** [comment]
Hi @fan0217 ,
Please refer that how did we update our demo to .NET 5

https://github.com/ant-design-blazor/ant-design-pro-blazor/pull/32/files#diff-d1baed79153fd9e236b1ec8ca276bb3c79cd37e8db168fdb8c23803fe04b3aa1

请参考这个PR我们是如何更新我们的demo到.NET 5的
