### ISSUE TITLE
Unable to start debugging properly when creating the server-side project from the template

### ISSUE THREAD

**Issue by gmij** [ant-design-blazor/ant-design-pro-blazor#37]
Properties/launchSettings.json中的
"inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
该参数， 仅适用于WebAssembly项目，对于serverside项目，不应附加该参数。

详见：MSDN
https://docs.microsoft.com/zh-cn/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio

附加该参数后，会导致 
1. 启动调试时打开的浏览器页面，空白。 无法直接加载项目
![image](https://user-images.githubusercontent.com/22893579/99936907-44aa6600-2d9f-11eb-94fa-055ea189f5a5.png)

2. IDE大概20秒左右，会提示
![image](https://user-images.githubusercontent.com/22893579/99936879-33615980-2d9f-11eb-9134-7837c993a80d.png)

移除该参数后，调试恢复正常。

**Comment by ElderJames** [comment]
Thanks for contacting us @gmij ,
We will fix it later.
