### ISSUE TITLE
 RightContent 中放置了Message ，抽屉打开时提示在遮罩层下面

### ISSUE THREAD

**Issue by huhangfei** [ant-design-blazor/ant-design-pro-blazor#38]
### 异常

- BasicLayout 中的 SettingDrawer 开启时  与 RightContent 中的Message，会造成重复弹出全局Message 。
- 移除SettingDrawer 后，保留RightContent 中的Message，全局Message在抽屉打开时，会显示再遮罩层下面。

### 正常
移除SettingDrawer 后,将RightContent 中的Message移至BasicLayout 就正常了；

**Comment by zxyao145** [comment]
@huhangfei 

您好，Message组件 属于容器组件，在一个项目中**仅仅需要在根组件使用一次**即可。由于 Message 组件都是共享使用 MessageService 的，所以重复使用该组件会造成重复弹出全局Message 。我看了下 ant-design-pro-blazor 和 pro-layout 的代码，里面对于 Message组件 的使用是存在有问题的，我们会在尽快修复这个问题，感谢您的联系！
