### ISSUE TITLE
使用最新版本模板，生成项目builder报错

### ISSUE THREAD

**Issue by spancechou** [ant-design-blazor/ant-design-pro-blazor#41]
![image](https://user-images.githubusercontent.com/52477178/100254055-d15e4b00-2f7c-11eb-8491-8e65c8a44c8c.png)
使用 dotnet new antdesign --host=server 命令生成

**Comment by mutouzdl** [comment]
我也遇到过，把项目的obj和bin文件夹删除后，重新试试，我这边是这么解决的。
