### ISSUE TITLE
Issue with Select Component wiht net5

### ISSUE THREAD

**Issue by michalss** [ant-design-blazor/ant-design-pro-blazor#48]
After a new AntBlazor Tempalte with net5 this happend.. Any fix for this pls ?

![image](https://user-images.githubusercontent.com/1000729/100505054-f74a4200-316c-11eb-8dcc-fc8986c4707f.png)

**Comment by michalss** [comment]
there is millions of issues with templating.. :(

![image](https://user-images.githubusercontent.com/1000729/100509786-61afb200-316e-11eb-8d82-a3ff0ec40d16.png)

**Comment by ElderJames** [comment]
Thanks for contacting us @michalss 
Our select has been refactored and has a little break changes.  You can take a look at the workaround

**Comment by michalss** [comment]
can you please fix your template as well. I know how to fix it, but to be honest a dont want to go for all 450 errors and fix it 1 by 1. Thx a lot

**Comment by ElderJames** [comment]
Hi @michalss , thank you for your interest in our component library.

We have published the 0.1.4 template in #47 , please update it and try  again.

**Comment by michalss** [comment]
Thank you, yr almost there but still it cannot be build:

![image](https://user-images.githubusercontent.com/1000729/100524589-ad3b7d80-31b9-11eb-841b-479b09d1ac7d.png)

**Comment by ElderJames** [comment]
Please delete the `obj` folder and try again.

**Comment by michalss** [comment]
Nope i did try this, same result.. :( I dont really need it, but i think it could be useful even for others, so to make it work would be great. So i reported this issue on the first place..
