### ISSUE TITLE
水平菜单模式下，菜单切换异常

### ISSUE THREAD

**Issue by ram16g** [ant-design-blazor/ant-design-pro-blazor#50]
![err](https://user-images.githubusercontent.com/11473136/100558267-b414de00-32e8-11eb-8c69-646deff95cc1.png)

**Comment by lingku7080** [comment]
这边实践中在blazor webassembly 模式下操作很卡，使用Task方法也会有很大延迟。不知为何。

**Comment by ElderJames** [comment]
Hi @ram16g , 这个问题已经修复了。

**Comment by ram16g** [comment]
2020-12-21 刚才试了一下，这个问题依然存在 ，antd-blazor 已经更新到最新的版本了 0.5.0-nightly-2012210848
