### ISSUE TITLE
遇到这个问题该怎么解决啊 , 一直在加载界面进不去

### ISSUE THREAD

**Issue by lexigua** [ant-design-blazor/ant-design-pro-blazor#51]
Failed to find a valid digest in the 'integrity' attribute for resource 'https://localhost:5001/_framework/AntDesign.dll' with computed SHA-256 integrity 'YAe67wlzT9CxEWOsx9Wmis/lBSV6uh/suhtKF8/pmtw='. The resource has been blocked.
遇到这个问题该怎么解决啊 , 一直在加载界面进不去

**Comment by yoli799480165** [comment]
建议关闭vs后清空项目下的bin和obj文件夹。然后再重新编译。
如果还是不能解决，你可以按照如下方法进行操作，重新安装最新模板，使用新模板重新创建项目，将原有项目文件迁移过去，再重新编译。

**Comment by lexigua** [comment]
谢谢, 清空重新编译, 解决问题了
