### ISSUE TITLE
Suggestion: Fully qualify all Tooltip components

### ISSUE THREAD

**Issue by anddrzejb** [ant-design-blazor/ant-design-pro-blazor#67]
I keep getting compilation errors from my VS `'Tooltip' is an ambiguous reference between 'AntDesign.Tooltip' and AntDesign.Charts.Tooltip'`.
![image](https://user-images.githubusercontent.com/6518006/105678521-eeb88280-5ef5-11eb-8ccc-590fba225fdd.png)

 It runs but obstructs my project (and I imagine anyone's project). I do not think it adds to user experience. I raised [this issue #36](https://github.com/ant-design-blazor/ant-design-charts-blazor/issues/36)) but the response was to fully qualify the components. So my suggestion is to also fully qualify the `Tooltip` component in:
* `Components/GlobalHeader/RightContent.razor`
* `Pages/Account/Center/Components/Applications/Applications.razor`
* `Pages/Account/Center/Components/AvatarList/AvatarList.razor`
* `Pages/Dashboard/Analysis/MiniProgress.razor`
* `Pages/List/Search/Applications/Applications.razor`

**Comment by ElderJames** [comment]
It's OK. This problem is very confusing.

At the beginning of the ant design blazor project, we were naming components with the `Ant` prefix, but then realized it wasn't very concise and removed it. I thought we could use the prefix as an option for fallback.

**Comment by anddrzejb** [comment]
Ok. I will create a PR with the change. But I suspect other users are going  to find that approach annoying.

**Comment by ElderJames** [comment]
Yes, I can't believe this is actually the default practice of blazor 😂
