### ISSUE TITLE
How to remove the footer

### ISSUE THREAD

**Issue by bodzilla** [ant-design-blazor/ant-design-pro-blazor#80]
How would one remove the footer which shows the below content:

Ant Design ProAnt Design
Copyright  2019 蚂蚁金服体验技术部出品

**Comment by ElderJames** [comment]
Thanks for contacting us @bodzilla , you can set your own footer with `FooterRender` template.

```
<AntDesign.Pro.Layout.BasicLayout 
    Logo="@("https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg")"
    MenuData="MenuData">
    <RightContentRender>
        <AntDesign.Pro.Template.Components.RightContent />
    </RightContentRender>
    <ChildContent>
        @Body
    </ChildContent>
    <FooterRender></FooterRender>  // <--- this line
</AntDesign.Pro.Layout.BasicLayout>
<SettingDrawer />

```

**Comment by bodzilla** [comment]
> Thanks for contacting us @bodzilla , you can set your own footer with `FooterRender` template.
> 
> ```
> <AntDesign.Pro.Layout.BasicLayout 
>     Logo="@("https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg")"
>     MenuData="MenuData">
>     <RightContentRender>
>         <AntDesign.Pro.Template.Components.RightContent />
>     </RightContentRender>
>     <ChildContent>
>         @Body
>     </ChildContent>
>     <FooterRender></FooterRender>  // <--- this line
> </AntDesign.Pro.Layout.BasicLayout>
> <SettingDrawer />
> ```

Thank you very much for this. I couldn't find any documentation on this at all so appreciate your help! :)

**Comment by ElderJames** [comment]
Yes, we would add a documentation later ..
