### ISSUE TITLE
How to remove the logo in BasicLayout 

### ISSUE THREAD

**Issue by 15951836388** [ant-design-blazor/ant-design-pro-blazor#82]
How to remove the logo in BasicLayout

**Comment by ElderJames** [comment]
Please override the `HeaderDom` template.

**Comment by 15951836388** [comment]
现在即使去掉logo字段，依然有显示

    <AntDesign.Pro.Layout.BasicLayout MenuData="_menuData">
输入图片说明

**Comment by 15951836388** [comment]
能说下，具体要如何做吗？这块不太熟悉

**Comment by 15951836388** [comment]
能说下，具体要如何做吗？这块不太熟悉

**Comment by ElderJames** [comment]
请通过Logo传入字符串或者模板

**Comment by NessfertIndia** [comment]
Can we set the Logo from a folder location  rather than setting a url? My logo is inside wwwroot folder

**Comment by ElderJames** [comment]
Yes, you can pass your image url to the `Logo` parameter of the `BasicLayout`  component.

**Comment by NessfertIndia** [comment]
Logo="@("WhiteLogo.png")" worked for me . Where the "WhiteLogo.png"  is inside the root folder 

My Layout looks like below now

```
<AntDesign.ProLayout.BasicLayout     
    Logo="@("WhiteLogo.png")"
    MenuData="_menuData">
    <RightContentRender>
        <KHL.DataCloud.ClientPortal.Components.RightContent />
    </RightContentRender>
    <ChildContent>
        @Body
    </ChildContent>
    <FooterRender>
        <FooterView Copyright="Company" Links="Links"></FooterView>
    </FooterRender>
</AntDesign.ProLayout.BasicLayout>
```

But how can i change the header colour ?
