### ISSUE TITLE
[NoticeIcon > NoticeList] EvenCallBack to get the data of Item in NoticeList

### ISSUE THREAD

**Issue by datnguyen89** [ant-design-blazor/ant-design-pro-blazor#83]
Please add EvenCallBack to get the data of Item in NoticeList: some thing like OnClick or OnClickItem
Thank you!
![NoticeList](https://user-images.githubusercontent.com/55984933/116069512-a9068400-a6b5-11eb-80c1-8ae0dfe8408a.png)

**Comment by ElderJames** [comment]
I have add OnItemClick for ListItem , please try 0.1.3
