### ISSUE TITLE
swtich,checkbox的样式异常

### ISSUE THREAD

**Issue by scugzbc** [ant-design-blazor/ant-design-pro-blazor#95]
Swtich,CheckBox的样式异常，而这两个组件的使用频率非常高，而在AntDesign的blazor组件库里是没有这个问题的。
分析了一下，也还不确定是什么原因。希望能调一下。
![image](https://user-images.githubusercontent.com/8499347/135385295-e663732b-b266-4608-bc87-8aed8fed954c.png)
正确的应该是这样：
![image](https://user-images.githubusercontent.com/8499347/135385372-3130ddaa-29e4-4891-8693-9cfac0a76ac5.png)

**Comment by ElderJames** [comment]
Thanks for contracting us @scugzbc . 

Please provider a demo to reproduce this issue.

**Comment by scugzbc** [comment]
只需要把Switch,CheckBox放入FormItem 标签就可以重现了。




   郑贝贝&nbsp; &nbsp; &nbsp; tel:18771032842&nbsp; &nbsp; &nbsp; &nbsp; QQ:21489598&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;微信:scugzbc
 地址：洪山区珞瑜路312号双恒创业园行政楼五楼5104室&nbsp; &nbsp;邮编：443200
 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design-blazor/ant-design-pro-blazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月30日(星期四) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design-blazor/ant-design-pro-blazor] swtich,checkbox的样式异常 (#95)





 
Thanks for contracting us @scugzbc .
 
Please provider a demo to reproduce this issue.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ElderJames** [comment]
I can't reproduce this issue.

It is fine at the demo doc https://ant-design-blazor.gitee.io/zh-CN/components/form#components-form-demo-size

![image](https://user-images.githubusercontent.com/7550366/137596407-9ad3639c-b57b-48c7-948a-af86c9712640.png)
