### ISSUE TITLE
从模板创建出来的示例无法正确运行。

### ISSUE THREAD

**Issue by seamusic** [ant-design-blazor/ant-design-pro-blazor#98]
dotnet new antdesignadmin --host server --force 正常
 dotnet new antdesign --host=server --full 运行报错。

`An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area: }.
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)`

**Comment by ElderJames** [comment]
Thanks for contacting us @seamusic . Yes, the template missing the Server/Pages/_Host.cshtml, you can create this file ant copy the content from https://github.com/ant-design-blazor/ant-design-pro-blazor/blob/master/.template.config/templates/server/Pages/_Host.cshtml

**Comment by ElderJames** [comment]
fixed in #111
