### ISSUE TITLE
AntDesign.ProLayout升级到0.1.8后运行报错

### ISSUE THREAD

**Issue by ltstudio168** [ant-design-blazor/ant-design-pro-blazor#99]
恢复到0.1.0后可正常运行。

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'AntDesign.interop.domInfoHelper.getInfo' ('domInfoHelper' was undefined).
      Error: Could not find 'AntDesign.interop.domInfoHelper.getInfo' ('domInfoHelper' was undefined).

**Comment by ElderJames** [comment]
Hi @ltstudio168 , please clear your browser cache.
